## Birthday Parties
#### Member
1. YMCA Member or Community Member registers online for a Birthday Party

#### System
2. An email is automatically sent to Heidi alerting her that someone has registered for a party.

#### Heidi
3. Log into Daxko. In the Child Care tab, click on manage programs. Then, click on Birthday Party program- Q&A for all, expand view, and on the answers for the registrant.

4. The type of party, time, and date are now visible. This information should be added to calendars.

5. When adding to Community Room Calendar write: Reserved for a Birthday Party

6. When adding to the Gym Calendar write: 1/2 Gym Reserved for a Birthday Party

#### Anne
7. When adding to the Pool Calendar write: Birthday Party Scheduled- Open Swim Still Available. (Please note that a birthday party will only be added to the pool calendar when there will be more than 20 swimmers attending)

#### Heidi
8. Add the fill in information in the Gym or Pool Party info email and email to party parent/ guardian.

9. Request the t-shirt size and place it on top of the birthday party bin with a note that includes: Birthday child's name & party date.

10. If a gym party was chosen, gather requested equipment into a rolling blue garbage bin. Keep this bin in the cage prior to the party with a note that includes: Birthday child's name & party date.

11. Send out an email to lead staff team with the following information: subject: Birthday Party Scheduled. Body text includes: Date, time, chosen activity, approx. number of children and adults, and birthday child's name.

#### Anne
12. If there is a gym party, communicate with the Wellness team that the divider must be put down on birthday party date. As well, the Wellness team must get the blue garbage bin with equipment out of the cage and roll it to the back half of the gym before the party begins.

13. If there is a pool party, communicate with the Lifeguard staff, and schedule extra lifeguards for that day if needed.

#### Jesse
14. Communicate with Janitorial staff that after the birthday party they will need to check the community room, and other spaces used during the party. If there are damages sustained from the party, or extra mess that is not cleaned, janitorial staff will take photos and let Jesse know. Communicate with Heidi so she can charge additional fees when needed.

#### Suzanne
15. Communicate with member services team that when the party comes in: a vacuum, party t-shirt for the birthday child, and the birthday party bin should be provided to the registrants.

16. Communicate with member services team that everyone that comes to the party must be checked into the facility. Party attendees will have multiple options of how they can enter their information. 
* If they are members, they can just stop at the front desk and check in.
* If they are not members, they can go online on their own and set up a community member account.
* Non-members can fill out the birthday party form prior to the party and bring it to the MS desk on entry
* Non-members can request a birthday party form and fill it out upon arrival.

17. Communicate with member service team that upon arrival, registrants will need to make sure all party attendants are checked into Daxko. Party attendants will be given instructions prior to the party on how to enter/update their information in Daxko. Ms will also need to take photos of all party attendees that do not already have one in the system.

#### Heidi
18. On Monday or Tuesday of the following week, email out a Thank You to the party registrant for celebrating at the YMCA.
