project:
  type: website
  output-dir: docs

website:
  title: "SOP Handbook"
  navbar:
    left:
      - href: index.qmd
        text: Master
      - href: MS.qmd
        text: Member Services
      - href: ChildCare.qmd
        text: Child Care
      - href: Maintenence.qmd
        text: Maintenence
      - href: Administration.qmd
        text: Administration
      - href: Aquatics.qmd
        text: Aquatics
      - href: forms.qmd
        text: Forms
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



