# Basic Information & Overview
*  You are the first and last experience for a member; make sure to greet them as they come in and leave. Friendliness makes a difference.

* Members in the building come first. Voicemails can be checked and we can get back to phone calls.

* Personal cell phone use is restricted when at the front desk. If you need to make a call, walkie the MOD to cover while you step in the back.

* Do not leave the desk unattended. If you need to use the restroom, get a drink, or grab food, walkie the MOD up to cover while you step away.

*  Supervisors determine when breaks should be taken in accordance with staffing and program requirements. Breaks cannot be added to extend a meal period or used to end work early.

*  A short duration rest break is available within each period of four consecutive work hours. This includes bathroom breaks, phone calls and any other times you step away from the front desk. Food can be eaten up at the front desk if needed, but make sure this is done at slower times during your shift.

*  If scheduled to work eight or more consecutive hours, a 30-minute unpaid meal break is required. MOD is responsible for coverage of these breaks.

*  There are mailboxes for different staff members in the back behind Member Services in case you need to give forms or other info to someone. The mailbox for each individual is the box to the right of their name.

*  New information and updates are put in the MS information Binder. You should also get emails, so please make sure to check your email, and the binger, during your shift.

#### Daxko Training Site Information

Each staff member has their own log in to the Daxko Training site.

The training site can be found if you click Daxko Operations (Training). Keep this page separate from the live version of Daxko. All edits made on the training site do not actually apply and are purely for practice.

#### Member Service Staff Email

All MS Staff have their own email and should check it at the beginning and throughout their shift (at least hourly). This can be accessed through the Outlook application.

This email should only be used for internal purposes, which include:

* Updates for Member Services Staff 
* To communicate with Lead Team Staff who are not in the building 
* Internal YMCA business 

Do NOT use this email to communicate directly with members. 

Please use email to communicate with other internal staff members instead of leaving them post-it notes, as post-it’s can get lost. 

Make sure to include member’s name, contact information and details regarding reason for email when sending a message to a staff member. 

Please make sure to send any Member Services/Membership questions or issue to both Suzanne & Megan, so that one of us can answer. 

#### Schedule & Time Off Requests

All communications regarding schedules will be sent to staff’s personal email. Please make sure you can receive emails from megan@northfieldymca.org. 

Schedules are created at least one month at a time and should be sent out mid-way through the previous month. 

Time off requests should be submitted at least 2 months in advance to help with the scheduling process to make sure shifts are covered. If anything comes up unexpectedly once the schedule is complete, then you are responsible for finding coverage, by either switching with someone or finding someone to cover for you. Contact information for Member Services staff is in the Information Binder. 

Timekeeping & Exception Forms

You should use the ADP app to clock in and out. This is to be done in the laundry room when you pick up/drop off your walkie. There is a Quick Clock on the app that can be used without having to sign in, otherwise, once you sign in you will click on either Start Work, or End Work. 
If you miss punching in or out, there are exception forms that can be filled out with the missed time. These are in the Laundry Room on the whiteboard. Fill out the form and put it in Suzanne’s mailbox before the end of the pay period. Pay periods are the 1st-15th, and the 15th-Last day. You will get paid on the 15th and the Last day of the month. 

#### Confidential Information

All information in Daxko is always confidential.

Daxko and membership information should only be given to adults (18+) that are listed on the unit.
* There are some situations where it might seem ok to give out personal information to someone, but please remember that giving personal info to anyone that is not listed on the unit, and over 18, is not approved.

Daxko information in a membership, especially billing and scholarship information, should never be given to minors. Occasionally a minor will come in to use the Y, and the membership in not currently active. In this case, do no give out billing info or scholarship info to the minor. Make sure that you have the parent/guardian’s correct contact information and email the admin team so they can follow up with the parent/guardian. 

You should never give out any youth program participant information to any adult that is not listed on the child’s unit. 

All youth program participant registration info is confidential, and only to be given out to the parent/guardian that is listed on the unit.

* There are instances in youth programming where a parent/guardian may call asking about a child’s participation in a program. If that parent/guardian is not listed on the unit, they may not be given that information. This may be a situation where he/she is not allowed to see the child. In this case, always remember to check notes on the unit. 

* When a parent calls to ask for information about a child’s registration, please make sure to verify the identity of the adult first. 

If you are unsure of someone’s identity, it is OK to ask for their date of birth, address, email or phone number to verify. 

#### Insurance Information

Members can sign up to get reimbursed from their insurance company if they come a certain number of times a month, depending on the company. 

Insurance forms are in the drawer under the front desk. There are separate folders for each of the insurance companies. 

Insurance forms should be filled out, initialed and signed. Make a copy of the front of their insurance card and they need to attach a voided check. 

Completed forms, which include the Enrollment form, voided check and copy of insurance card, can be put in Megan’s mailbox. 

We do not take Blue Cross Blue Shield.  

We do not participate in SilverSneakers, Renew Active, One Pass, and Active & Fit. 

We do have a Silver & Fit option, applications are in the drawer. 

#### Safety Protocols
There is an Emergency Action Procedures binder in the front desk drawer. This has all procedures that should be followed in different types of emergencies. 

The Safety committee will be performing drills throughout the year to ensure that all members of staff know the emergency procedures. 

Incident Reporting – in the back of the EAP binder there is a sheet that outlines what types of incidents need to be reported and how to do that. There are blank Incident Reports in the back pocket of the EAP binder. 

There is a sheet in the back of the EAP binder that provides direction on what to do when you need to clean up blood or other bodily fluids on non-carpeted surfaces. 

There is an emergency intercom for the pool deck on the wall behind the front desk. This is so if there is an emergency in the pool the lifeguard can contact the front quickly. If this goes off, follow the intercom protocols that are above the intercom. 

#### Self-Check In Station
There is a Self-Check In station set up at the 2nd front desk computer, this is to be used for active members only, anyone else coming in for any other reason should check in with Member Services staff. There are signs up front to help direct members. 

Member Services staff should still pay attention to everyone coming in the building, and should be where most people are checking in. The self-check in station is a tool to help with the busy times when there is not double coverage up at the front. This is not an excuse to not pay attention, you should still be greeting everyone when they come in. 

Member Services should monitor the self-check in station to make sure those checking in are active. 

Regarding rosters: You can use the “Who is Here?” list to see who is in the building to compare to the roster. You can call a MOD up to help monitor when you know a class is starting if that is helpful.  

#### Tour Information

If someone calls and requests a tour, let them know they can come in anytime for a tour, or if they want to set up a time they can do that as well. If they set up a specific day/time, email the Member Services staff member who will be on duty at that time and let them know the day/time that the visitor will be coming in, along with their name. 

If someone just walks in and requests a tour, let them know you will get someone to show them around. Have the visitor fill out the Membership Inquiry form, which is on the small clipboards at the front of the drawer.  

If there is only 1 member services staff member, then walkie Wellness to see if they can come to the front and give a tour.  

If there are 2 member services staff members, one of you can give the tour. 

## Department Contact List
Member Services: Suzanne

* Membership/ Scholarship questions
* Daxko or Administrative concerns

Health & Wellness and Aquatics: Erik & Anne

* Wellness Floor: Erik
* Group Exercise: Erik
* Swimming Lessons: Anne
* Open Swim/ Lap Swim: Anne
* Personal Training: Anne

 Youth Development: Heidi & Izzy
* Child Watch
* Birthday Parties
* Camp
* Youth in Government

 Building & Grounds: Jesse

* Maintenance
* Deliveries
* Building projects




