# Be Our Guest Passes

#### MS Team Member

1. If a guest comes in with a Be Our Guest Pass, they are able to use the facility
2. Have them fill out a Program Participant/ Community Member form. These are found in the appropriate folder in the drawer beneath the front desk
3. Add them as a Community Member if they are not in Daxko, or activate them as Community Member if they are
4. Click on Balance Due in the upper right-hand corner
5. Click on Add One-Time Fees button
6. Check the box next to Be Our Guest Pass. The amount will be zero dollars, but this is for tracking purposes
7. Click the Add Fees button at the bottom of the page. It will take you back to the Balance Due page. No actual payment needs to be taken as this is free
8. Go back to the Membership Information page
9. Check them in, no key fob is required
10. Add a note to their account that they came in on a Be Our Guest Pass
11. Sign initials and date the Community Member/ Program Participant form
12. Staple the Be Our Guest Pass to the form
13. Put form in the Be Our Guest folder in the top of the Membership File Cabinet
